### ISSUE TITLE
Neural Network in C++ video

### ISSUE THREAD

**Issue by yacineMahdid** [yacineMahdid/ml-xp#1]
Last video I did on ffnn in Java could be improved. I think the first step would be to do it i C++ since its more relevant performance-wise.

**TODO:**
- [ ] Create a representation of a Neuron
- [ ] Create a representation of a Layer
- [ ] Create a representation of a FF Neural Network
- [ ] Implement backpropagation in the FF Neural Network

That would be the minimum for the video.

**EXTRA**
- [ ] Implement a training class to load data into it
- [ ] Train the Neural Network on MNIST dataset to recognize digits
