### ISSUE TITLE
Introduction to Data Science Projects Video

### ISSUE THREAD

**Issue by yacineMahdid** [yacineMahdid/ml-xp#2]
Idea would be to show how to get started doing data science with a simple kaggle project.
Titanic would be a good idea to start.

**TODO**
- [x] Frame the problem.
- [x] Look at what data we have to solve the problem.
- [ ] Transform whatever we need to transform.
- [ ] Explore the transformed data to look for correlation.
- [ ] Shortlist a bunch of classifier that could work for the problem.
- [ ] Transform the data to fit the classifiers.
- [ ] Train the classifier and optimize.
